### ISSUE TITLE
synetbuild crashes when calling subprocess.check_output(["jobs", "-p"])

### ISSUE THREAD

**Issue by liushuotong** [hcli007/SNN_pipeline#5]
---
name: Bug Report
about: Report critical initialization crash in synetbuild
title: Critical: `synetbuild` crashes on subprocess.check_output(["jobs", "-p"]) during initialization
labels: 'bug, high-priority, crash'

---

## Environment Summary
- **OS**: Ubuntu 24.04.2 LTS (Linux 6.8.0-53-generic)
- **Python**: 3.8.15 (Conda)
- **Relevant Packages**:
  - subprocess32==3.5.4
- **Installation**: `conda create -n snn_pipeline`

---

## Reproduction Steps
1. Environment setup:
   ```bash
   conda activate snn_pipeline
   ```
2. Prepare test dataset:
   - Valid `species_list` file
   - Directory structure:
     ```
     test-data/
     ```
3. Execute command:
   ```bash
   synetbuild -i ./test-data/species_list -d ./test-data/ -o ./step3
   ```

---

## Observed Behavior
**Immediate crash** during initialization phase with traceback:

```python
Traceback (most recent call last):
  File "/opt/conda/envs/snn_pipeline/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/conda/envs/snn_pipeline/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/conda/envs/snn_pipeline/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/envs/snn_pipeline/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'jobs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synetbuild.py", line 57, in synet_build
    running = subprocess.check_output(["jobs", "-p"], universal_newlines=True)
KeyboardInterrupt
```

**Key Observations**:
- 100% reproducibility rate across multiple test environments
- Error persists even with valid input configurations
- Subsequent `KeyboardInterrupt` is red herring (artifact of failed subprocess handling)

---

## Expected Behavior
Successful initialization with proper process validation and progression to SynNet construction steps.

---

### Fault Location
`synetbuild.py` Line 57:
```python
running = subprocess.check_output(["jobs", "-p"], universal_newlines=True)
```

### Root Causes
1. **Invalid Subprocess Invocation**:
   - `jobs` is a [shell builtin command](https://www.gnu.org/software/bash/manual/html_node/Job-Control-Builtins.html) unavailable to `subprocess` without `shell=True`
   - Results in `FileNotFoundError` exception

2. **Exception Handling Deficiency**:
   - Uncaught exception leads to undefined state
   - Subsequent code paths attempt to access undefined `running` variable

3. **Architectural Impact**:
   ```mermaid
   graph TD
     A[subprocess.check_output] --> B{Valid Process Check?}
     B -->|Failure| C[Unhandled Exception]
     C --> D[Partial Initialization]
     D --> E[Unrecoverable State]
   ```

---

### Tested Solutions
| Approach | Implementation | Result | Risk Assessment |
|----------|----------------|--------|-----------------|
| **Nullification** | `running = ""` | Success | Low (temporarily bypasses process check) |

---

**Comment by hcli007** [comment]
Very detailed report. This issue seems similar to the feedback from another user earlier. The cause of the problem appears to be that the latest version of the Ubuntu system does not have the `jobs` command built-in. I addressed this issue in version 0.2.5. For more details, please refer to [(https://github.com/hcli007/SNN_pipeline/issues/2)]
I noticed that the error occurs on **line 57**, which indicates that you might still be using an earlier version of snn_pipeline. You can try installing the latest version of snn_pipeline using `pip install`.

**Comment by liushuotong** [comment]
I uninstalled the original version and reinstalled the software, but the original program was still hanging. I outlined the possible reasons.

```bash
(snn_pipline) liushuotong@liushuotong:/media/liushuotong/163A49433A4920DB/SNN$ pip uninstall snn_pipeline -y
Found existing installation: snn_pipeline 0.2.5
Uninstalling snn_pipeline-0.2.5:
  Successfully uninstalled snn_pipeline-0.2.5
(snn_pipline) liushuotong@liushuotong:/media/liushuotong/163A49433A4920DB/SNN$ pip install --no-cache-dir snn_pipeline==0.2.5
Collecting snn_pipeline==0.2.5
  Downloading snn_pipeline-0.2.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: biopython>=1.79 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from snn_pipeline==0.2.5) (1.83)
Requirement already satisfied: igraph>=0.1.14 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from snn_pipeline==0.2.5) (0.11.8)
Requirement already satisfied: networkx>=2.6.3 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from snn_pipeline==0.2.5) (3.1)
Requirement already satisfied: numpy>=1.21.2 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from snn_pipeline==0.2.5) (1.24.4)
Requirement already satisfied: pandas>=1.4.1 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from snn_pipeline==0.2.5) (2.0.3)
Requirement already satisfied: scikit-learn>=1.3.2 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from snn_pipeline==0.2.5) (1.3.2)
Requirement already satisfied: texttable>=1.6.2 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from igraph>=0.1.14->snn_pipeline==0.2.5) (1.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from pandas>=1.4.1->snn_pipeline==0.2.5) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from pandas>=1.4.1->snn_pipeline==0.2.5) (2025.1)
Requirement already satisfied: tzdata>=2022.1 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from pandas>=1.4.1->snn_pipeline==0.2.5) (2025.1)
Requirement already satisfied: scipy>=1.5.0 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from scikit-learn>=1.3.2->snn_pipeline==0.2.5) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from scikit-learn>=1.3.2->snn_pipeline==0.2.5) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from scikit-learn>=1.3.2->snn_pipeline==0.2.5) (3.5.0)
Requirement already satisfied: six>=1.5 in /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.1->snn_pipeline==0.2.5) (1.17.0)
Downloading snn_pipeline-0.2.5-py3-none-any.whl (39 kB)
Installing collected packages: snn_pipeline
Successfully installed snn_pipeline-0.2.5
(snn_pipline) liushuotong@liushuotong:/media/liushuotong/163A49433A4920DB/SNN$ find /home/liushuotong/miniconda3/envs/snn_pipline -name "synetbuild.py"
/home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages/snn_pipeline/synetbuild.py
(snn_pipline) liushuotong@liushuotong:/media/liushuotong/163A49433A4920DB/SNN$ grep "job" /home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages/snn_pipeline/synetbuild.py
            running = subprocess.check_output(["jobs", "-p"], universal_newlines=True)
(snn_pipline) liushuotong@liushuotong:/media/liushuotong/163A49433A4920DB/SNN$ 
```

```bash
synetbuild -i ./test-data/species_list -d ./test-data/ -o ./step3
```
The `jobs` command is a shell built-in, which is **only effective in interactive shell sessions** (e.g., a terminal where users manually input commands).

Job control refers to the ability to selectively stop (suspend) the execution of processes and continue (resume) their execution at a later point. A user typically employs this facility via **an interactive interface** supplied jointly by the operating system kernel’s terminal driver and Bash. (From Link: https://www.gnu.org/software/bash/manual/html_node/Job-Control-Basics.html)

```bash
(snn_pipline) liushuotong@liushuotong:/media/liushuotong/163A49433A4920DB/SNN$ synetbuild -i ./test-data/species_list -d ./test-data/ -o ./step3
Execution parameters:	/home/liushuotong/miniconda3/envs/snn_pipline/bin/synetbuild -i ./test-data/species_list -d ./test-data/ -o ./step3
^CTraceback (most recent call last):
  File "/home/liushuotong/miniconda3/envs/snn_pipline/bin/synetbuild", line 8, in <module>
    sys.exit(main())
  File "/home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages/snn_pipeline/synetbuild.py", line 208, in main
    synet_build(complete_path(args.species_namelist_file), complete_path(args.data_path), complete_path(args.out_dir),
  File "/home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/site-packages/snn_pipeline/synetbuild.py", line 57, in synet_build
    running = subprocess.check_output(["jobs", "-p"], universal_newlines=True)
  File "/home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/liushuotong/miniconda3/envs/snn_pipline/lib/python3.8/subprocess.py", line 1655, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
KeyboardInterrupt

(snn_pipline) liushuotong@liushuotong:/media/liushuotong/163A49433A4920DB/SNN$ 
```

The jobs command relies on the ​interactive job control feature of the shell. When called via Python's subprocess (or in scripts), it executes in a non-interactive context with no access to the parent shell's job table. This is why the command hangs indefinitely and requires a Ctrl+C to terminate.

For cross-platform compatibility, replace jobs -p with system-agnostic process management methods (e.g., ps, pgrep, or Python's os/subprocess modules).

I sincerely appreciate your dedication of time and expertise to this collaborative analysis. The community benefits greatly from contributors like you taking the time to engage with technical challenges.

**Comment by hcli007** [comment]
The purpose of the error code is to prevent task overload in the system. Its logic is to detect whether your computer or server has available CPUs to execute tasks. This criterion is related to the -p parameter you initially entered for synetbuild. The default value of p is 8. The script will remain in a dormant state and will not proceed until the criterion is met.
In version 0.2.5 of `snn_pipeline`, if the script detects that there is no `jobs` command in your system, it will skip the execution of this step. Since the `jobs` command is not available in Ubuntu systems, the script should normally have moved on to execute the subsequent code.
